dataset:
  type: 'kitti'
  data_dir: 'data/KITTI3D'
  root_dir: '.'
  dense_depth_dir: 'data/KITTI3D/training/depth_dense_lrru_my_version_2.0clip'
  label_dir: 'data/KITTI3D/training/label_2'
  eval_cls: ['Car']
#  eval_cls: ['Car','Pedestrian','Cyclist']
  batch_size: 16
  num_workers: 16
  class_merging: False
  use_dontcare: False
  use_3d_center: True
  writelist: ['Car']
  random_flip: 0.5
  random_crop: 0.5
  scale: 0.4
  shift: 0.1
  drop_last_val: False

model:
  type: 'DID'
  backbone: 'dla34'
  neck: 'DLAUp'

optimizer:
  type: 'adam'
  lr: 0.001
  weight_decay: 0.00001

lr_scheduler:
  warmup: True  # 5 epoches, cosine warmup, init_lir=0.00001 in default
  decay_rate: 0.1
  decay_list: [90, 120]

trainer:
  max_epoch: 150
  eval_start: 90
  eval_frequency: 1 # evaluation interval (in epoch)
  save_frequency: 1 # checkpoint save interval (in epoch)
  disp_frequency: 50 # display interval (in batch)
  log_dir: 'work_dirs/kitti_models/logs/only_car_lrru_clip_transformer_encoder_another_attention_2'
  out_dir: 'work_dirs/kitti_models/output/only_car_lrru_clip_transformer_encoder_another_attention_2'
tester:
  threshold: 0.2  # confidence filter
  out_dir: './tmp_test/test'
  resume_model: '' # pre-trained model path



